### ISSUE TITLE
откройте терминал и запустите команду

### ISSUE THREAD

**Issue by KarelWintersky** [FrontenderMagazine/grunt-is-not-weird-and-hard#2]
> Когда конфигурация concat окажется на своем месте, откройте терминал и запустите команду:
> `grunt`
> И, смотрите, что происходит! 

И - ничего не происходит.
`"grunt" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.`

win7, все установлено по предыдущим инструкциям.

**Comment by iamstarkov** [comment]
Привет, а что терминал говорит на вот эти строки?

```
node -v
npm -v
```

**Comment by KarelWintersky** [comment]
Спасибо за оперативность :)

> node -v

v0.12.2 (ставил по ссылке "Большая зеленая кнопка инсталл на сайте nodejs)

> npv -v

2.7.4

В качестве терминала на у меня FAR, `%PATH%` проверена :)

**Comment by iamstarkov** [comment]
Нужно больше <del>золота</del> информации, милорд!

```
➜  ~  npm rm -g grunt grunt-cli
unbuild grunt@0.4.5
unbuild grunt-cli@0.1.13
➜  ~  npm install -g grunt-cli
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
grunt-cli@0.1.13 /usr/local/lib/node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.5)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
➜  ~  grunt --version
grunt-cli v0.1.13
```

Прости, я не смог воспроизвести =( Ты пробовал спрашивать на Stackoverflow или в issue гранта?

**Comment by KarelWintersky** [comment]
Нет, я только-только решил освоить _это_ 

> npm rm -g grunt grunt-cli
> npm WARN uninstall not installed in `C:\Users\Arris\AppData\Roaming\npm\node_modules`: "grunt"
> unbuild grunt-cli@0.1.13

Что забавно, такого пути действительно нет, есть только до 
`C:\Users\Arris\AppData\Roaming\npm\`

> npm install -g grunt-cli

Z:\home\LibDB_>npm install -g grunt-cli
C:\Users\Arris\AppData\Roaming\npm\grunt -> C:\Users\Arris\AppData\Roaming\npm\node_modules\grunt-cli\bin
\grunt
grunt-cli@0.1.13 C:\Users\Arris\AppData\Roaming\npm\node_modules\grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.5)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

> grunt --version
> "grunt" не является внутренней или внешней
> командой, исполняемой программой или пакетным файлом.

**Comment by KarelWintersky** [comment]
Для issue гранта я слишком плохо знаю английский. Читаю нормально, пишу плохо. 

По поводу пути - а фиг его знает, почему так... СЕйчас снесу, поставлю заново... По моему это виндекапец виновата.

**Comment by iamstarkov** [comment]
> По поводу пути - а фиг его знает,

это кажется дело всё таки в %path%, так как винда не там ищет бинарники

я знаю, кто может помочь! мы тут как раз недавно обсуждали проблемы с виндой

**Comment by KarelWintersky** [comment]
Кстати, я правильно понимаю, что грантом можно с той же лёгкостью собрать (а потом скомпилить в html/pdf) и текстовый проект, набранный в маркдауне?

**Comment by KarelWintersky** [comment]
Проблема, кажется, решилась. Корень всех зол - windows terminal. А именно - переменная окружения %PATH% ставится вне терминала. И если она вдруг изменилась - терминалу об этом никто не скажет.  Поэтому "закрыть терминал", "открыть терминал". 

_Если ничего не помогает, прочтите наконец документацию_

Но ничего, еще что-нибудь вылезет.

Спасибо.

**Comment by iamstarkov** [comment]
> Кстати, я правильно понимаю, что грантом можно с той же лёгкостью собрать (а потом скомпилить в html/pdf) и текстовый проект, набранный в маркдауне?

да, цепочка такая md→html→pdf

**Comment by iamstarkov** [comment]
Круто, что всё решилось

**Comment by roose** [comment]
С %PATH% это же всем известно, что перезапустить терминал нужно, и вообще grunt зло, используйте gulp :smile:

**Comment by KarelWintersky** [comment]
Я только-только грантом пользоваться научился, какой уж тут гульп? :)

**Comment by iamstarkov** [comment]
Он проще, и если уж начинать сейчас, то сразу с галпа

**Comment by KarelWintersky** [comment]
Почитал о галпе ( http://frontender.info/no-need-to-grunt-take-a-gulp-of-fresh-air/ ) и, если честно, не увидел внятных преимуществ. 

Уточню задачи, которые я стал решать грантом: склейка множества файлов в один и преобрование markdown->html.

Кстати, не могу найти - можно ли брать последовательность склейки не из gruntfile, а из внешнего индекс-файла? Желательно, чтобы поддерживался импорт (других индекс-файлов из имеющегося).

**Comment by iamstarkov** [comment]
@KarelWintersky галп быстрее и писать джаваскрипт понятнее, чем конфиг гранта

**Comment by KarelWintersky** [comment]
> писать джаваскрипт понятнее, чем конфиг гранта

ну не знаааю... :)
Я почитал конфиги галпа и я нифига не понял, честное слово :) 
Это видимо какое-то хитрое вуду для профессиональных разработчиков

**Comment by iamstarkov** [comment]
на вкус и цвет =)
